name: CI Build and Publish – Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  validate-api-spec-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: current

      - name: Validate apiSpec version is fixed
        run: ./gradlew validateApiSpecVersions

  ci-release:
    uses: ./.github/workflows/ci-build-publish.yml
    secrets:
      AZURE_DEVOPS_ARTIFACT_USERNAME: ${{ secrets.AZURE_DEVOPS_ARTIFACT_USERNAME }}
      AZURE_DEVOPS_ARTIFACT_TOKEN: ${{ secrets.AZURE_DEVOPS_ARTIFACT_TOKEN }}
      HMCTS_ADO_PAT: ${{ secrets.HMCTS_CP_ADO_PAT }}
    with:
      is_release: true
      is_publish: true
      trigger_docker: true
      trigger_deploy: true
